export const BASE_URL = "http://localhost:8000"
// export const BASE_URL = "https://passwordmanager-production.up.railway.app"
// export const QUICKSIGN_URL="https://localhost:5173"
export const QUICKSIGN_URL="https://quick-sign.vercel.app"
export const QUICKSIGN_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE1ZjlmZjMzMTdjZjgxNGE3ZjI5YTYiLCJpYXQiOjE2NzkxNjE4Njd9.G95ddr3telwGEjRZBeVLKxLW4kDAWcKC0uRKC6mTHak"